complexity:
  LongMethod:
    active: false
  TooManyFunctions:
    active: false

style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ProtectedMemberInFinalClass:
    active: false
