# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
trust-domain: app-services
task-priority: highest

taskgraph:
  register: app_services_taskgraph:register
  repositories:
    appservices:
      name: "Application Services"
  cached-task-prefix: project.application-services
  decision-parameters: 'app_services_taskgraph:get_decision_parameters'

workers:
  aliases:
    b-linux:
      provisioner: 'app-services-{level}'
      implementation: docker-worker
      os: linux
      worker-type: 'b-linux'
    images:
      provisioner: 'app-services-{level}'
      implementation: docker-worker
      os: linux
      worker-type: 'images'

scriptworker:
  scope-prefix: project:mozilla:application-services:releng
